sudo: false
dist: trusty
language: java
jdk: openjdk11

env: GRAAL_HOME=./graalvm-ce-19.2.1
    
# https://github.com/travis-ci/travis-ci/issues/8408
before_install:
  - unset _JAVA_OPTIONS

install:
  - java pro_wrapper.java version
  - wget https://github.com/oracle/graal/releases/download/vm-19.2.1/graalvm-ce-linux-amd64-19.2.1.tar.gz
  - tar zxvf graalvm-ce-linux-amd64-19.2.1.tar.gz
  - $GRAAL_HOME/bin/gu install native-image

script:
  - ./pro/bin/pro
  - bash ./execute-jdk11.sh
  - bash ./execute-graal.sh
  - bash ./generate-jlink.sh
  - bash ./execute-jlink.sh
  - bash ./generate-native-image.sh
  - bash ./execute-native-image.sh
